name: Deploy to Azure App Service - Play Junction

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy-to-production:
        description: 'Deploy to Production'
        required: true
        default: 'false'
      deploy-to-test:
        description: 'Deploy to test'
        required: true
        default: 'false'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          npm install && npm i -g nx && nx run-many --target=build --projects=play-junction-be,play-junction-fe


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: dist

  deploy-develop:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Develop'
      url: ${{steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App (Develop)'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Play-Junction-development'
          slot-name: 'Production'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEVELOPMENT}}

  deploy-test:
    runs-on: ubuntu-latest
    needs: deploy-develop
    if: ${{ github.event.inputs.deploy-to-test == 'true' && github.event_name == 'workflow_dispatch' }}
    environment:
      name: 'Test'
      url: ${{steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Manual approval
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Approve deployment to test"
          echo "To approve, set 'deploy-to-test' input to 'true' in the workflow dispatch event."
          echo "Input value for deploy-to-test: ${{ github.event.inputs.deploy-to-test }}"

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App (Test)'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Play-Junction-Test'
          slot-name: 'Production'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST}}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-test
    if: ${{ github.event.inputs.deploy-to-production == 'true' && github.event_name == 'workflow_dispatch' }}
    environment:
      name: 'Production'

    steps:
      - name: Manual approval
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Approve deployment to Production"
          echo "To approve, set 'deploy-to-production' input to 'true' in the workflow dispatch event."
          echo "Input value for deploy-to-production: ${{ github.event.inputs.deploy-to-production }}"

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App (Production)'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Play-Junction'
          slot-name: 'Production'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
